import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = join(repoRoot, 'sources.json');
const outputRoot = join(repoRoot, 'rules', 'mihomo');
const userAgent = 'zyxtoworld-rules-builder/1.0';
const retryCount = 3;

async function fetchText(url) {
  let lastError;
  for (let attempt = 1; attempt <= retryCount; attempt += 1) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 90000);
    try {
      const response = await fetch(url, { headers: { 'user-agent': userAgent }, signal: controller.signal });
      if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
      return await response.text();
    } catch (error) {
      lastError = error;
      if (attempt < retryCount) await new Promise(resolveWait => setTimeout(resolveWait, attempt * 1500));
    } finally {
      clearTimeout(timer);
    }
  }
  throw new Error(`${url}: ${lastError?.message || 'fetch failed'}`);
}

function unquote(value) {
  let text = value.trim();
  if ((text.startsWith("'") && text.endsWith("'")) || (text.startsWith('"') && text.endsWith('"'))) {
    text = text.slice(1, -1);
  }
  return text.trim();
}

function parseRuleLine(rawLine, dropTypes = []) {
  let line = rawLine.replace(/^\uFEFF/, '').trim();
  if (!line || line.startsWith('#') || line === 'payload:') return [];
  line = line.replace(/^[-]\s+/, '').trim();
  line = unquote(line);
  if (!line || line === 'payload:') return [];

  if (line.startsWith('+.')) return [`DOMAIN-SUFFIX,${line.slice(2)}`];
  if (/^[A-Za-z0-9*_-]+(\.[A-Za-z0-9*_-]+)+$/.test(line)) return [`DOMAIN,${line}`];

  const pieces = line.split(',').map(part => part.trim());
  const type = String(pieces[0] || '').toUpperCase();
  if (dropTypes.map(value => value.toUpperCase()).includes(type)) return [];
  const allowed = new Set(['DOMAIN', 'DOMAIN-SUFFIX', 'DOMAIN-KEYWORD', 'IP-CIDR', 'IP-CIDR6', 'IP-ASN', 'PROCESS-NAME', 'PROCESS-PATH']);
  if (!allowed.has(type) || !pieces[1]) return [];
  return [`${type},${pieces.slice(1).join(',')}`];
}

function parseSource(text, source) {
  const rules = [];
  for (const line of text.split(/\r?\n/)) rules.push(...parseRuleLine(line, source.dropTypes || []));
  return rules;
}

function domainParts(value) {
  return value.toLowerCase().split('.').filter(Boolean);
}

function isCoveredBySuffix(domain, suffixes, includeSelf = false) {
  const parts = domainParts(domain);
  const start = includeSelf ? 0 : 1;
  for (let index = start; index < parts.length - 1; index += 1) {
    if (suffixes.has(parts.slice(index).join('.'))) return true;
  }
  return false;
}

function minimizeRules(input) {
  const unique = [...new Set(input)];
  const suffixes = new Set(unique.filter(rule => rule.startsWith('DOMAIN-SUFFIX,')).map(rule => rule.slice('DOMAIN-SUFFIX,'.length).toLowerCase()));
  const result = [];
  for (const rule of unique) {
    const [type, value] = rule.split(',', 2);
    if ((type === 'DOMAIN-SUFFIX' && isCoveredBySuffix(value, suffixes)) || (type === 'DOMAIN' && isCoveredBySuffix(value, suffixes, true))) {
      if (type === 'DOMAIN-SUFFIX' || suffixes.has(value.toLowerCase())) continue;
    }
    result.push(rule);
  }
  const order = new Map(['DOMAIN', 'DOMAIN-SUFFIX', 'DOMAIN-KEYWORD', 'IP-CIDR', 'IP-CIDR6', 'IP-ASN', 'PROCESS-NAME', 'PROCESS-PATH'].map((type, index) => [type, index]));
  return result.sort((left, right) => {
    const leftType = left.split(',', 1)[0];
    const rightType = right.split(',', 1)[0];
    return (order.get(leftType) ?? 99) - (order.get(rightType) ?? 99) || left.localeCompare(right);
  });
}

function renderYaml(rules) {
  return `# Generated by scripts/build-rules.mjs. Do not edit manually.\npayload:\n${rules.map(rule => `  - ${rule}`).join('\n')}\n`;
}

const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
await mkdir(outputRoot, { recursive: true });
const metadata = { generatedAt: new Date().toISOString(), sources: {}, outputs: {} };

for (const [name, sources] of Object.entries(manifest.sources)) {
  const collected = [];
  metadata.sources[name] = [];
  for (const source of sources) {
    process.stdout.write(`fetch ${name}: ${source.url}\n`);
    const text = await fetchText(source.url);
    const parsed = parseSource(text, source);
    for (const rule of parsed) collected.push(rule);
    metadata.sources[name].push({ url: source.url, source: source.source, rules: parsed.length });
  }
  const rules = minimizeRules(collected);
  const outputPath = join(outputRoot, `${name}.yaml`);
  await writeFile(outputPath, renderYaml(rules), 'utf8');
  metadata.outputs[name] = { path: `rules/mihomo/${name}.yaml`, rules: rules.length };
  process.stdout.write(`write ${name}: ${rules.length} rules\n`);
}

await writeFile(join(repoRoot, 'rules', 'manifest.json'), `${JSON.stringify(metadata, null, 2)}\n`, 'utf8');